<?php 
return [
	['perm' => 'group_update', 'method' => 'post'],
	['perm' => 'group_delete', 'method' => 'get'],
	['perm' => 'user_delete', 'method' => 'get'],
	['perm' => 'user_update', 'method' => 'post'],
	['perm' => 'permission_update', 'method' => 'post'],
	['perm' => 'permission_delete', 'method' => 'get'],
	['perm' => 'user_update_status', 'method' => 'post'],
	['perm' => 'setting_update', 'method' => 'post'],
	['perm' => 'menu_save_ordering', 'method' => 'post'],
	['perm' => 'menu_update', 'method' => 'post'],
	['perm' => 'menu_delete', 'method' => 'get'],
	['perm' => 'menu_type_delete', 'method' => 'get'],
	['perm' => 'api_user_update', 'method' => 'post'],
	['perm' => 'api_user_update_profile', 'method' => 'post'],
	['perm' => 'api_user_delete', 'method' => 'post'],
	['perm' => 'api_group_update', 'method' => 'post'],
	['perm' => 'api_group_delete', 'method' => 'post'],
	['perm' => 'page_delete', 'method' => 'get'],
	['perm' => 'form_delete', 'method' => 'get'],
	['perm' => 'keys_delete', 'method' => 'get'],
	['perm' => 'crud_delete', 'method' => 'get'],
	['perm' => 'aauth_users_delete', 'method' => 'get'],
	['perm' => 'aauth_users_update', 'method' => 'post'],
	['perm' => 'aauth_groups_delete', 'method' => 'get'],
	['perm' => 'aauth_groups_update', 'method' => 'post'],
	['perm' => 'menu_delete', 'method' => 'get'],
	['perm' => 'menu_groups_update', 'method' => 'post'],
	['perm' => 'extension_deactivate', 'method' => 'get'],
	['perm' => 'extension_activate', 'method' => 'get'],
	['perm' => 'extension_install', 'method' => 'get'],
];