<style>
    .loading-hide {
        margin-left: 10px;
        display: none
    }

    .label-warning{
        color: #212529;
        background-color: #ffc209;
        border-color: #ffc209;
    }
    .label-success{
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }
    .label-silver{
        color: #444;
        background-color: #cfcfcf;
        border-color: #cfcfcf;
    }
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){

   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tbl_bank/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Notifications<small></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Notifications</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <a class="btn btn-flat btn-success" href="<?= site_url('administrator/notifications/index/read')?>">Read</a>
                        <a class="btn btn-flat btn-warning" href="<?= site_url('administrator/notifications/index/unread')?>">Unread</a>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Notifications</h3>
                     <h5 class="widget-user-desc"> <i class="label bg-yellow"><?= $pms_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tbl_bank" id="form_tbl_bank" action="<?= base_url('administrator/tbl_bank/index'); ?>">


                  <div class="table-responsive">
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                            <th>#ID</th>
                            <th>Date</th>
                            <th>From</th>
                            <th>Message</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tbl_bank">
                     <?php foreach($pms as $pm): ?>
                        <tr>
                            <td class="requester-name"><label class="label label-success"><?=$pm->title;?></label></td>
                            <td class="wedding-date">
                                <label class="label label-silver"><?=$pm->date_sent;?></label>
                            </td>
                            <?php
                                if($pm->sender_id == 0){
                                    $from = 'Asiatop HRIS';
                                } else {
                                    $sender = db_get_data('aauth_users','id = '.$pm->sender_id);
                                    $from = $sender->full_name;
                                }
                            ?>
                            <td class="requester-name"> <?=$from;?></td>
                            <td class="requester-message"><?php 
                              if(strpos($pm->message, 'rejected')) {
                                echo '<font style="color:#dd4b39">'.$pm->message.'</font>';
                              } else if(strpos($pm->message, 'approved')) {
                                echo '<font style="color:#28a745">'.$pm->message.'</font>';
                              } else {
                                echo $pm->message;
                              }
                            ?></td>
                            <td class="requester-status">
                              <label class="label label-<?=(($pm->date_read != null) ? 'success' : 'warning');?>"><?=(($pm->date_read != null) ? 'Read' : 'Unread');?></label>
                            </td>
                            <?php $vlq_id = explode('-', $pm->title)[1]; ?>
                            <td class="requester-action">
                                <a href="<?= site_url('administrator/notifications/view/' . $pm->id); ?>" class="label-default"><i class="fa fa-eye "></i> View</a><br>
                                <a href="javascript:void(0);" data-href="<?= site_url('administrator/notifications/delete/' . $pm->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                            </td>
                        </tr>
                     <?php endforeach; ?>
                     <?php if ($pms_counts == 0) :?>
                        <tr>
                        <td colspan="100">
                        Notifications data is not available
                        </td>
                        </tr>
                     <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){

    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tbl_bank').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tbl_bank/delete?' + serialize_bulk;
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>
